// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: People.proto

package protobuf;

public interface AddressOrBuilder extends
    // @@protoc_insertion_point(interface_extends:Address)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>string street = 1;</code>
   * @return The street.
   */
  java.lang.String getStreet();
  /**
   * <code>string street = 1;</code>
   * @return The bytes for street.
   */
  com.google.protobuf.ByteString
      getStreetBytes();

  /**
   * <code>int32 number = 2;</code>
   * @return The number.
   */
  int getNumber();
}
