// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: People.proto

package protobuf;

public interface PeopleOrBuilder extends
    // @@protoc_insertion_point(interface_extends:People)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>repeated .Person person = 1;</code>
   */
  java.util.List<protobuf.Person> 
      getPersonList();
  /**
   * <code>repeated .Person person = 1;</code>
   */
  protobuf.Person getPerson(int index);
  /**
   * <code>repeated .Person person = 1;</code>
   */
  int getPersonCount();
  /**
   * <code>repeated .Person person = 1;</code>
   */
  java.util.List<? extends protobuf.PersonOrBuilder> 
      getPersonOrBuilderList();
  /**
   * <code>repeated .Person person = 1;</code>
   */
  protobuf.PersonOrBuilder getPersonOrBuilder(
      int index);
}
