// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: People.proto

package protobuf;

/**
 * Protobuf type {@code Person}
 */
public final class Person extends
    com.google.protobuf.GeneratedMessageV3 implements
    // @@protoc_insertion_point(message_implements:Person)
    PersonOrBuilder {
private static final long serialVersionUID = 0L;
  // Use Person.newBuilder() to construct.
  private Person(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
    super(builder);
  }
  private Person() {
    name_ = "";
    address_ = java.util.Collections.emptyList();
    mobile_ = com.google.protobuf.LazyStringArrayList.EMPTY;
    email_ = com.google.protobuf.LazyStringArrayList.EMPTY;
  }

  @java.lang.Override
  @SuppressWarnings({"unused"})
  protected java.lang.Object newInstance(
      UnusedPrivateParameter unused) {
    return new Person();
  }

  @java.lang.Override
  public final com.google.protobuf.UnknownFieldSet
  getUnknownFields() {
    return this.unknownFields;
  }
  private Person(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    this();
    if (extensionRegistry == null) {
      throw new java.lang.NullPointerException();
    }
    int mutable_bitField0_ = 0;
    com.google.protobuf.UnknownFieldSet.Builder unknownFields =
        com.google.protobuf.UnknownFieldSet.newBuilder();
    try {
      boolean done = false;
      while (!done) {
        int tag = input.readTag();
        switch (tag) {
          case 0:
            done = true;
            break;
          case 10: {
            java.lang.String s = input.readStringRequireUtf8();

            name_ = s;
            break;
          }
          case 18: {
            if (!((mutable_bitField0_ & 0x00000001) != 0)) {
              address_ = new java.util.ArrayList<protobuf.Address>();
              mutable_bitField0_ |= 0x00000001;
            }
            address_.add(
                input.readMessage(protobuf.Address.parser(), extensionRegistry));
            break;
          }
          case 26: {
            java.lang.String s = input.readStringRequireUtf8();
            if (!((mutable_bitField0_ & 0x00000002) != 0)) {
              mobile_ = new com.google.protobuf.LazyStringArrayList();
              mutable_bitField0_ |= 0x00000002;
            }
            mobile_.add(s);
            break;
          }
          case 34: {
            java.lang.String s = input.readStringRequireUtf8();
            if (!((mutable_bitField0_ & 0x00000004) != 0)) {
              email_ = new com.google.protobuf.LazyStringArrayList();
              mutable_bitField0_ |= 0x00000004;
            }
            email_.add(s);
            break;
          }
          default: {
            if (!parseUnknownField(
                input, unknownFields, extensionRegistry, tag)) {
              done = true;
            }
            break;
          }
        }
      }
    } catch (com.google.protobuf.InvalidProtocolBufferException e) {
      throw e.setUnfinishedMessage(this);
    } catch (com.google.protobuf.UninitializedMessageException e) {
      throw e.asInvalidProtocolBufferException().setUnfinishedMessage(this);
    } catch (java.io.IOException e) {
      throw new com.google.protobuf.InvalidProtocolBufferException(
          e).setUnfinishedMessage(this);
    } finally {
      if (((mutable_bitField0_ & 0x00000001) != 0)) {
        address_ = java.util.Collections.unmodifiableList(address_);
      }
      if (((mutable_bitField0_ & 0x00000002) != 0)) {
        mobile_ = mobile_.getUnmodifiableView();
      }
      if (((mutable_bitField0_ & 0x00000004) != 0)) {
        email_ = email_.getUnmodifiableView();
      }
      this.unknownFields = unknownFields.build();
      makeExtensionsImmutable();
    }
  }
  public static final com.google.protobuf.Descriptors.Descriptor
      getDescriptor() {
    return protobuf.PeopleOuterClass.internal_static_Person_descriptor;
  }

  @java.lang.Override
  protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internalGetFieldAccessorTable() {
    return protobuf.PeopleOuterClass.internal_static_Person_fieldAccessorTable
        .ensureFieldAccessorsInitialized(
            protobuf.Person.class, protobuf.Person.Builder.class);
  }

  public static final int NAME_FIELD_NUMBER = 1;
  private volatile java.lang.Object name_;
  /**
   * <code>string name = 1;</code>
   * @return The name.
   */
  @java.lang.Override
  public java.lang.String getName() {
    java.lang.Object ref = name_;
    if (ref instanceof java.lang.String) {
      return (java.lang.String) ref;
    } else {
      com.google.protobuf.ByteString bs = 
          (com.google.protobuf.ByteString) ref;
      java.lang.String s = bs.toStringUtf8();
      name_ = s;
      return s;
    }
  }
  /**
   * <code>string name = 1;</code>
   * @return The bytes for name.
   */
  @java.lang.Override
  public com.google.protobuf.ByteString
      getNameBytes() {
    java.lang.Object ref = name_;
    if (ref instanceof java.lang.String) {
      com.google.protobuf.ByteString b = 
          com.google.protobuf.ByteString.copyFromUtf8(
              (java.lang.String) ref);
      name_ = b;
      return b;
    } else {
      return (com.google.protobuf.ByteString) ref;
    }
  }

  public static final int ADDRESS_FIELD_NUMBER = 2;
  private java.util.List<protobuf.Address> address_;
  /**
   * <code>repeated .Address address = 2;</code>
   */
  @java.lang.Override
  public java.util.List<protobuf.Address> getAddressList() {
    return address_;
  }
  /**
   * <code>repeated .Address address = 2;</code>
   */
  @java.lang.Override
  public java.util.List<? extends protobuf.AddressOrBuilder> 
      getAddressOrBuilderList() {
    return address_;
  }
  /**
   * <code>repeated .Address address = 2;</code>
   */
  @java.lang.Override
  public int getAddressCount() {
    return address_.size();
  }
  /**
   * <code>repeated .Address address = 2;</code>
   */
  @java.lang.Override
  public protobuf.Address getAddress(int index) {
    return address_.get(index);
  }
  /**
   * <code>repeated .Address address = 2;</code>
   */
  @java.lang.Override
  public protobuf.AddressOrBuilder getAddressOrBuilder(
      int index) {
    return address_.get(index);
  }

  public static final int MOBILE_FIELD_NUMBER = 3;
  private com.google.protobuf.LazyStringList mobile_;
  /**
   * <code>repeated string mobile = 3;</code>
   * @return A list containing the mobile.
   */
  public com.google.protobuf.ProtocolStringList
      getMobileList() {
    return mobile_;
  }
  /**
   * <code>repeated string mobile = 3;</code>
   * @return The count of mobile.
   */
  public int getMobileCount() {
    return mobile_.size();
  }
  /**
   * <code>repeated string mobile = 3;</code>
   * @param index The index of the element to return.
   * @return The mobile at the given index.
   */
  public java.lang.String getMobile(int index) {
    return mobile_.get(index);
  }
  /**
   * <code>repeated string mobile = 3;</code>
   * @param index The index of the value to return.
   * @return The bytes of the mobile at the given index.
   */
  public com.google.protobuf.ByteString
      getMobileBytes(int index) {
    return mobile_.getByteString(index);
  }

  public static final int EMAIL_FIELD_NUMBER = 4;
  private com.google.protobuf.LazyStringList email_;
  /**
   * <code>repeated string email = 4;</code>
   * @return A list containing the email.
   */
  public com.google.protobuf.ProtocolStringList
      getEmailList() {
    return email_;
  }
  /**
   * <code>repeated string email = 4;</code>
   * @return The count of email.
   */
  public int getEmailCount() {
    return email_.size();
  }
  /**
   * <code>repeated string email = 4;</code>
   * @param index The index of the element to return.
   * @return The email at the given index.
   */
  public java.lang.String getEmail(int index) {
    return email_.get(index);
  }
  /**
   * <code>repeated string email = 4;</code>
   * @param index The index of the value to return.
   * @return The bytes of the email at the given index.
   */
  public com.google.protobuf.ByteString
      getEmailBytes(int index) {
    return email_.getByteString(index);
  }

  private byte memoizedIsInitialized = -1;
  @java.lang.Override
  public final boolean isInitialized() {
    byte isInitialized = memoizedIsInitialized;
    if (isInitialized == 1) return true;
    if (isInitialized == 0) return false;

    memoizedIsInitialized = 1;
    return true;
  }

  @java.lang.Override
  public void writeTo(com.google.protobuf.CodedOutputStream output)
                      throws java.io.IOException {
    if (!com.google.protobuf.GeneratedMessageV3.isStringEmpty(name_)) {
      com.google.protobuf.GeneratedMessageV3.writeString(output, 1, name_);
    }
    for (int i = 0; i < address_.size(); i++) {
      output.writeMessage(2, address_.get(i));
    }
    for (int i = 0; i < mobile_.size(); i++) {
      com.google.protobuf.GeneratedMessageV3.writeString(output, 3, mobile_.getRaw(i));
    }
    for (int i = 0; i < email_.size(); i++) {
      com.google.protobuf.GeneratedMessageV3.writeString(output, 4, email_.getRaw(i));
    }
    unknownFields.writeTo(output);
  }

  @java.lang.Override
  public int getSerializedSize() {
    int size = memoizedSize;
    if (size != -1) return size;

    size = 0;
    if (!com.google.protobuf.GeneratedMessageV3.isStringEmpty(name_)) {
      size += com.google.protobuf.GeneratedMessageV3.computeStringSize(1, name_);
    }
    for (int i = 0; i < address_.size(); i++) {
      size += com.google.protobuf.CodedOutputStream
        .computeMessageSize(2, address_.get(i));
    }
    {
      int dataSize = 0;
      for (int i = 0; i < mobile_.size(); i++) {
        dataSize += computeStringSizeNoTag(mobile_.getRaw(i));
      }
      size += dataSize;
      size += 1 * getMobileList().size();
    }
    {
      int dataSize = 0;
      for (int i = 0; i < email_.size(); i++) {
        dataSize += computeStringSizeNoTag(email_.getRaw(i));
      }
      size += dataSize;
      size += 1 * getEmailList().size();
    }
    size += unknownFields.getSerializedSize();
    memoizedSize = size;
    return size;
  }

  @java.lang.Override
  public boolean equals(final java.lang.Object obj) {
    if (obj == this) {
     return true;
    }
    if (!(obj instanceof protobuf.Person)) {
      return super.equals(obj);
    }
    protobuf.Person other = (protobuf.Person) obj;

    if (!getName()
        .equals(other.getName())) return false;
    if (!getAddressList()
        .equals(other.getAddressList())) return false;
    if (!getMobileList()
        .equals(other.getMobileList())) return false;
    if (!getEmailList()
        .equals(other.getEmailList())) return false;
    if (!unknownFields.equals(other.unknownFields)) return false;
    return true;
  }

  @java.lang.Override
  public int hashCode() {
    if (memoizedHashCode != 0) {
      return memoizedHashCode;
    }
    int hash = 41;
    hash = (19 * hash) + getDescriptor().hashCode();
    hash = (37 * hash) + NAME_FIELD_NUMBER;
    hash = (53 * hash) + getName().hashCode();
    if (getAddressCount() > 0) {
      hash = (37 * hash) + ADDRESS_FIELD_NUMBER;
      hash = (53 * hash) + getAddressList().hashCode();
    }
    if (getMobileCount() > 0) {
      hash = (37 * hash) + MOBILE_FIELD_NUMBER;
      hash = (53 * hash) + getMobileList().hashCode();
    }
    if (getEmailCount() > 0) {
      hash = (37 * hash) + EMAIL_FIELD_NUMBER;
      hash = (53 * hash) + getEmailList().hashCode();
    }
    hash = (29 * hash) + unknownFields.hashCode();
    memoizedHashCode = hash;
    return hash;
  }

  public static protobuf.Person parseFrom(
      java.nio.ByteBuffer data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static protobuf.Person parseFrom(
      java.nio.ByteBuffer data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static protobuf.Person parseFrom(
      com.google.protobuf.ByteString data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static protobuf.Person parseFrom(
      com.google.protobuf.ByteString data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static protobuf.Person parseFrom(byte[] data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static protobuf.Person parseFrom(
      byte[] data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static protobuf.Person parseFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static protobuf.Person parseFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }
  public static protobuf.Person parseDelimitedFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input);
  }
  public static protobuf.Person parseDelimitedFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
  }
  public static protobuf.Person parseFrom(
      com.google.protobuf.CodedInputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static protobuf.Person parseFrom(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }

  @java.lang.Override
  public Builder newBuilderForType() { return newBuilder(); }
  public static Builder newBuilder() {
    return DEFAULT_INSTANCE.toBuilder();
  }
  public static Builder newBuilder(protobuf.Person prototype) {
    return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
  }
  @java.lang.Override
  public Builder toBuilder() {
    return this == DEFAULT_INSTANCE
        ? new Builder() : new Builder().mergeFrom(this);
  }

  @java.lang.Override
  protected Builder newBuilderForType(
      com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
    Builder builder = new Builder(parent);
    return builder;
  }
  /**
   * Protobuf type {@code Person}
   */
  public static final class Builder extends
      com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
      // @@protoc_insertion_point(builder_implements:Person)
      protobuf.PersonOrBuilder {
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return protobuf.PeopleOuterClass.internal_static_Person_descriptor;
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return protobuf.PeopleOuterClass.internal_static_Person_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              protobuf.Person.class, protobuf.Person.Builder.class);
    }

    // Construct using protobuf.Person.newBuilder()
    private Builder() {
      maybeForceBuilderInitialization();
    }

    private Builder(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      super(parent);
      maybeForceBuilderInitialization();
    }
    private void maybeForceBuilderInitialization() {
      if (com.google.protobuf.GeneratedMessageV3
              .alwaysUseFieldBuilders) {
        getAddressFieldBuilder();
      }
    }
    @java.lang.Override
    public Builder clear() {
      super.clear();
      name_ = "";

      if (addressBuilder_ == null) {
        address_ = java.util.Collections.emptyList();
        bitField0_ = (bitField0_ & ~0x00000001);
      } else {
        addressBuilder_.clear();
      }
      mobile_ = com.google.protobuf.LazyStringArrayList.EMPTY;
      bitField0_ = (bitField0_ & ~0x00000002);
      email_ = com.google.protobuf.LazyStringArrayList.EMPTY;
      bitField0_ = (bitField0_ & ~0x00000004);
      return this;
    }

    @java.lang.Override
    public com.google.protobuf.Descriptors.Descriptor
        getDescriptorForType() {
      return protobuf.PeopleOuterClass.internal_static_Person_descriptor;
    }

    @java.lang.Override
    public protobuf.Person getDefaultInstanceForType() {
      return protobuf.Person.getDefaultInstance();
    }

    @java.lang.Override
    public protobuf.Person build() {
      protobuf.Person result = buildPartial();
      if (!result.isInitialized()) {
        throw newUninitializedMessageException(result);
      }
      return result;
    }

    @java.lang.Override
    public protobuf.Person buildPartial() {
      protobuf.Person result = new protobuf.Person(this);
      int from_bitField0_ = bitField0_;
      result.name_ = name_;
      if (addressBuilder_ == null) {
        if (((bitField0_ & 0x00000001) != 0)) {
          address_ = java.util.Collections.unmodifiableList(address_);
          bitField0_ = (bitField0_ & ~0x00000001);
        }
        result.address_ = address_;
      } else {
        result.address_ = addressBuilder_.build();
      }
      if (((bitField0_ & 0x00000002) != 0)) {
        mobile_ = mobile_.getUnmodifiableView();
        bitField0_ = (bitField0_ & ~0x00000002);
      }
      result.mobile_ = mobile_;
      if (((bitField0_ & 0x00000004) != 0)) {
        email_ = email_.getUnmodifiableView();
        bitField0_ = (bitField0_ & ~0x00000004);
      }
      result.email_ = email_;
      onBuilt();
      return result;
    }

    @java.lang.Override
    public Builder clone() {
      return super.clone();
    }
    @java.lang.Override
    public Builder setField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        java.lang.Object value) {
      return super.setField(field, value);
    }
    @java.lang.Override
    public Builder clearField(
        com.google.protobuf.Descriptors.FieldDescriptor field) {
      return super.clearField(field);
    }
    @java.lang.Override
    public Builder clearOneof(
        com.google.protobuf.Descriptors.OneofDescriptor oneof) {
      return super.clearOneof(oneof);
    }
    @java.lang.Override
    public Builder setRepeatedField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        int index, java.lang.Object value) {
      return super.setRepeatedField(field, index, value);
    }
    @java.lang.Override
    public Builder addRepeatedField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        java.lang.Object value) {
      return super.addRepeatedField(field, value);
    }
    @java.lang.Override
    public Builder mergeFrom(com.google.protobuf.Message other) {
      if (other instanceof protobuf.Person) {
        return mergeFrom((protobuf.Person)other);
      } else {
        super.mergeFrom(other);
        return this;
      }
    }

    public Builder mergeFrom(protobuf.Person other) {
      if (other == protobuf.Person.getDefaultInstance()) return this;
      if (!other.getName().isEmpty()) {
        name_ = other.name_;
        onChanged();
      }
      if (addressBuilder_ == null) {
        if (!other.address_.isEmpty()) {
          if (address_.isEmpty()) {
            address_ = other.address_;
            bitField0_ = (bitField0_ & ~0x00000001);
          } else {
            ensureAddressIsMutable();
            address_.addAll(other.address_);
          }
          onChanged();
        }
      } else {
        if (!other.address_.isEmpty()) {
          if (addressBuilder_.isEmpty()) {
            addressBuilder_.dispose();
            addressBuilder_ = null;
            address_ = other.address_;
            bitField0_ = (bitField0_ & ~0x00000001);
            addressBuilder_ = 
              com.google.protobuf.GeneratedMessageV3.alwaysUseFieldBuilders ?
                 getAddressFieldBuilder() : null;
          } else {
            addressBuilder_.addAllMessages(other.address_);
          }
        }
      }
      if (!other.mobile_.isEmpty()) {
        if (mobile_.isEmpty()) {
          mobile_ = other.mobile_;
          bitField0_ = (bitField0_ & ~0x00000002);
        } else {
          ensureMobileIsMutable();
          mobile_.addAll(other.mobile_);
        }
        onChanged();
      }
      if (!other.email_.isEmpty()) {
        if (email_.isEmpty()) {
          email_ = other.email_;
          bitField0_ = (bitField0_ & ~0x00000004);
        } else {
          ensureEmailIsMutable();
          email_.addAll(other.email_);
        }
        onChanged();
      }
      this.mergeUnknownFields(other.unknownFields);
      onChanged();
      return this;
    }

    @java.lang.Override
    public final boolean isInitialized() {
      return true;
    }

    @java.lang.Override
    public Builder mergeFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      protobuf.Person parsedMessage = null;
      try {
        parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        parsedMessage = (protobuf.Person) e.getUnfinishedMessage();
        throw e.unwrapIOException();
      } finally {
        if (parsedMessage != null) {
          mergeFrom(parsedMessage);
        }
      }
      return this;
    }
    private int bitField0_;

    private java.lang.Object name_ = "";
    /**
     * <code>string name = 1;</code>
     * @return The name.
     */
    public java.lang.String getName() {
      java.lang.Object ref = name_;
      if (!(ref instanceof java.lang.String)) {
        com.google.protobuf.ByteString bs =
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        name_ = s;
        return s;
      } else {
        return (java.lang.String) ref;
      }
    }
    /**
     * <code>string name = 1;</code>
     * @return The bytes for name.
     */
    public com.google.protobuf.ByteString
        getNameBytes() {
      java.lang.Object ref = name_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        name_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    /**
     * <code>string name = 1;</code>
     * @param value The name to set.
     * @return This builder for chaining.
     */
    public Builder setName(
        java.lang.String value) {
      if (value == null) {
    throw new NullPointerException();
  }
  
      name_ = value;
      onChanged();
      return this;
    }
    /**
     * <code>string name = 1;</code>
     * @return This builder for chaining.
     */
    public Builder clearName() {
      
      name_ = getDefaultInstance().getName();
      onChanged();
      return this;
    }
    /**
     * <code>string name = 1;</code>
     * @param value The bytes for name to set.
     * @return This builder for chaining.
     */
    public Builder setNameBytes(
        com.google.protobuf.ByteString value) {
      if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
      
      name_ = value;
      onChanged();
      return this;
    }

    private java.util.List<protobuf.Address> address_ =
      java.util.Collections.emptyList();
    private void ensureAddressIsMutable() {
      if (!((bitField0_ & 0x00000001) != 0)) {
        address_ = new java.util.ArrayList<protobuf.Address>(address_);
        bitField0_ |= 0x00000001;
       }
    }

    private com.google.protobuf.RepeatedFieldBuilderV3<
        protobuf.Address, protobuf.Address.Builder, protobuf.AddressOrBuilder> addressBuilder_;

    /**
     * <code>repeated .Address address = 2;</code>
     */
    public java.util.List<protobuf.Address> getAddressList() {
      if (addressBuilder_ == null) {
        return java.util.Collections.unmodifiableList(address_);
      } else {
        return addressBuilder_.getMessageList();
      }
    }
    /**
     * <code>repeated .Address address = 2;</code>
     */
    public int getAddressCount() {
      if (addressBuilder_ == null) {
        return address_.size();
      } else {
        return addressBuilder_.getCount();
      }
    }
    /**
     * <code>repeated .Address address = 2;</code>
     */
    public protobuf.Address getAddress(int index) {
      if (addressBuilder_ == null) {
        return address_.get(index);
      } else {
        return addressBuilder_.getMessage(index);
      }
    }
    /**
     * <code>repeated .Address address = 2;</code>
     */
    public Builder setAddress(
        int index, protobuf.Address value) {
      if (addressBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        ensureAddressIsMutable();
        address_.set(index, value);
        onChanged();
      } else {
        addressBuilder_.setMessage(index, value);
      }
      return this;
    }
    /**
     * <code>repeated .Address address = 2;</code>
     */
    public Builder setAddress(
        int index, protobuf.Address.Builder builderForValue) {
      if (addressBuilder_ == null) {
        ensureAddressIsMutable();
        address_.set(index, builderForValue.build());
        onChanged();
      } else {
        addressBuilder_.setMessage(index, builderForValue.build());
      }
      return this;
    }
    /**
     * <code>repeated .Address address = 2;</code>
     */
    public Builder addAddress(protobuf.Address value) {
      if (addressBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        ensureAddressIsMutable();
        address_.add(value);
        onChanged();
      } else {
        addressBuilder_.addMessage(value);
      }
      return this;
    }
    /**
     * <code>repeated .Address address = 2;</code>
     */
    public Builder addAddress(
        int index, protobuf.Address value) {
      if (addressBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        ensureAddressIsMutable();
        address_.add(index, value);
        onChanged();
      } else {
        addressBuilder_.addMessage(index, value);
      }
      return this;
    }
    /**
     * <code>repeated .Address address = 2;</code>
     */
    public Builder addAddress(
        protobuf.Address.Builder builderForValue) {
      if (addressBuilder_ == null) {
        ensureAddressIsMutable();
        address_.add(builderForValue.build());
        onChanged();
      } else {
        addressBuilder_.addMessage(builderForValue.build());
      }
      return this;
    }
    /**
     * <code>repeated .Address address = 2;</code>
     */
    public Builder addAddress(
        int index, protobuf.Address.Builder builderForValue) {
      if (addressBuilder_ == null) {
        ensureAddressIsMutable();
        address_.add(index, builderForValue.build());
        onChanged();
      } else {
        addressBuilder_.addMessage(index, builderForValue.build());
      }
      return this;
    }
    /**
     * <code>repeated .Address address = 2;</code>
     */
    public Builder addAllAddress(
        java.lang.Iterable<? extends protobuf.Address> values) {
      if (addressBuilder_ == null) {
        ensureAddressIsMutable();
        com.google.protobuf.AbstractMessageLite.Builder.addAll(
            values, address_);
        onChanged();
      } else {
        addressBuilder_.addAllMessages(values);
      }
      return this;
    }
    /**
     * <code>repeated .Address address = 2;</code>
     */
    public Builder clearAddress() {
      if (addressBuilder_ == null) {
        address_ = java.util.Collections.emptyList();
        bitField0_ = (bitField0_ & ~0x00000001);
        onChanged();
      } else {
        addressBuilder_.clear();
      }
      return this;
    }
    /**
     * <code>repeated .Address address = 2;</code>
     */
    public Builder removeAddress(int index) {
      if (addressBuilder_ == null) {
        ensureAddressIsMutable();
        address_.remove(index);
        onChanged();
      } else {
        addressBuilder_.remove(index);
      }
      return this;
    }
    /**
     * <code>repeated .Address address = 2;</code>
     */
    public protobuf.Address.Builder getAddressBuilder(
        int index) {
      return getAddressFieldBuilder().getBuilder(index);
    }
    /**
     * <code>repeated .Address address = 2;</code>
     */
    public protobuf.AddressOrBuilder getAddressOrBuilder(
        int index) {
      if (addressBuilder_ == null) {
        return address_.get(index);  } else {
        return addressBuilder_.getMessageOrBuilder(index);
      }
    }
    /**
     * <code>repeated .Address address = 2;</code>
     */
    public java.util.List<? extends protobuf.AddressOrBuilder> 
         getAddressOrBuilderList() {
      if (addressBuilder_ != null) {
        return addressBuilder_.getMessageOrBuilderList();
      } else {
        return java.util.Collections.unmodifiableList(address_);
      }
    }
    /**
     * <code>repeated .Address address = 2;</code>
     */
    public protobuf.Address.Builder addAddressBuilder() {
      return getAddressFieldBuilder().addBuilder(
          protobuf.Address.getDefaultInstance());
    }
    /**
     * <code>repeated .Address address = 2;</code>
     */
    public protobuf.Address.Builder addAddressBuilder(
        int index) {
      return getAddressFieldBuilder().addBuilder(
          index, protobuf.Address.getDefaultInstance());
    }
    /**
     * <code>repeated .Address address = 2;</code>
     */
    public java.util.List<protobuf.Address.Builder> 
         getAddressBuilderList() {
      return getAddressFieldBuilder().getBuilderList();
    }
    private com.google.protobuf.RepeatedFieldBuilderV3<
        protobuf.Address, protobuf.Address.Builder, protobuf.AddressOrBuilder> 
        getAddressFieldBuilder() {
      if (addressBuilder_ == null) {
        addressBuilder_ = new com.google.protobuf.RepeatedFieldBuilderV3<
            protobuf.Address, protobuf.Address.Builder, protobuf.AddressOrBuilder>(
                address_,
                ((bitField0_ & 0x00000001) != 0),
                getParentForChildren(),
                isClean());
        address_ = null;
      }
      return addressBuilder_;
    }

    private com.google.protobuf.LazyStringList mobile_ = com.google.protobuf.LazyStringArrayList.EMPTY;
    private void ensureMobileIsMutable() {
      if (!((bitField0_ & 0x00000002) != 0)) {
        mobile_ = new com.google.protobuf.LazyStringArrayList(mobile_);
        bitField0_ |= 0x00000002;
       }
    }
    /**
     * <code>repeated string mobile = 3;</code>
     * @return A list containing the mobile.
     */
    public com.google.protobuf.ProtocolStringList
        getMobileList() {
      return mobile_.getUnmodifiableView();
    }
    /**
     * <code>repeated string mobile = 3;</code>
     * @return The count of mobile.
     */
    public int getMobileCount() {
      return mobile_.size();
    }
    /**
     * <code>repeated string mobile = 3;</code>
     * @param index The index of the element to return.
     * @return The mobile at the given index.
     */
    public java.lang.String getMobile(int index) {
      return mobile_.get(index);
    }
    /**
     * <code>repeated string mobile = 3;</code>
     * @param index The index of the value to return.
     * @return The bytes of the mobile at the given index.
     */
    public com.google.protobuf.ByteString
        getMobileBytes(int index) {
      return mobile_.getByteString(index);
    }
    /**
     * <code>repeated string mobile = 3;</code>
     * @param index The index to set the value at.
     * @param value The mobile to set.
     * @return This builder for chaining.
     */
    public Builder setMobile(
        int index, java.lang.String value) {
      if (value == null) {
    throw new NullPointerException();
  }
  ensureMobileIsMutable();
      mobile_.set(index, value);
      onChanged();
      return this;
    }
    /**
     * <code>repeated string mobile = 3;</code>
     * @param value The mobile to add.
     * @return This builder for chaining.
     */
    public Builder addMobile(
        java.lang.String value) {
      if (value == null) {
    throw new NullPointerException();
  }
  ensureMobileIsMutable();
      mobile_.add(value);
      onChanged();
      return this;
    }
    /**
     * <code>repeated string mobile = 3;</code>
     * @param values The mobile to add.
     * @return This builder for chaining.
     */
    public Builder addAllMobile(
        java.lang.Iterable<java.lang.String> values) {
      ensureMobileIsMutable();
      com.google.protobuf.AbstractMessageLite.Builder.addAll(
          values, mobile_);
      onChanged();
      return this;
    }
    /**
     * <code>repeated string mobile = 3;</code>
     * @return This builder for chaining.
     */
    public Builder clearMobile() {
      mobile_ = com.google.protobuf.LazyStringArrayList.EMPTY;
      bitField0_ = (bitField0_ & ~0x00000002);
      onChanged();
      return this;
    }
    /**
     * <code>repeated string mobile = 3;</code>
     * @param value The bytes of the mobile to add.
     * @return This builder for chaining.
     */
    public Builder addMobileBytes(
        com.google.protobuf.ByteString value) {
      if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
      ensureMobileIsMutable();
      mobile_.add(value);
      onChanged();
      return this;
    }

    private com.google.protobuf.LazyStringList email_ = com.google.protobuf.LazyStringArrayList.EMPTY;
    private void ensureEmailIsMutable() {
      if (!((bitField0_ & 0x00000004) != 0)) {
        email_ = new com.google.protobuf.LazyStringArrayList(email_);
        bitField0_ |= 0x00000004;
       }
    }
    /**
     * <code>repeated string email = 4;</code>
     * @return A list containing the email.
     */
    public com.google.protobuf.ProtocolStringList
        getEmailList() {
      return email_.getUnmodifiableView();
    }
    /**
     * <code>repeated string email = 4;</code>
     * @return The count of email.
     */
    public int getEmailCount() {
      return email_.size();
    }
    /**
     * <code>repeated string email = 4;</code>
     * @param index The index of the element to return.
     * @return The email at the given index.
     */
    public java.lang.String getEmail(int index) {
      return email_.get(index);
    }
    /**
     * <code>repeated string email = 4;</code>
     * @param index The index of the value to return.
     * @return The bytes of the email at the given index.
     */
    public com.google.protobuf.ByteString
        getEmailBytes(int index) {
      return email_.getByteString(index);
    }
    /**
     * <code>repeated string email = 4;</code>
     * @param index The index to set the value at.
     * @param value The email to set.
     * @return This builder for chaining.
     */
    public Builder setEmail(
        int index, java.lang.String value) {
      if (value == null) {
    throw new NullPointerException();
  }
  ensureEmailIsMutable();
      email_.set(index, value);
      onChanged();
      return this;
    }
    /**
     * <code>repeated string email = 4;</code>
     * @param value The email to add.
     * @return This builder for chaining.
     */
    public Builder addEmail(
        java.lang.String value) {
      if (value == null) {
    throw new NullPointerException();
  }
  ensureEmailIsMutable();
      email_.add(value);
      onChanged();
      return this;
    }
    /**
     * <code>repeated string email = 4;</code>
     * @param values The email to add.
     * @return This builder for chaining.
     */
    public Builder addAllEmail(
        java.lang.Iterable<java.lang.String> values) {
      ensureEmailIsMutable();
      com.google.protobuf.AbstractMessageLite.Builder.addAll(
          values, email_);
      onChanged();
      return this;
    }
    /**
     * <code>repeated string email = 4;</code>
     * @return This builder for chaining.
     */
    public Builder clearEmail() {
      email_ = com.google.protobuf.LazyStringArrayList.EMPTY;
      bitField0_ = (bitField0_ & ~0x00000004);
      onChanged();
      return this;
    }
    /**
     * <code>repeated string email = 4;</code>
     * @param value The bytes of the email to add.
     * @return This builder for chaining.
     */
    public Builder addEmailBytes(
        com.google.protobuf.ByteString value) {
      if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
      ensureEmailIsMutable();
      email_.add(value);
      onChanged();
      return this;
    }
    @java.lang.Override
    public final Builder setUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return super.setUnknownFields(unknownFields);
    }

    @java.lang.Override
    public final Builder mergeUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return super.mergeUnknownFields(unknownFields);
    }


    // @@protoc_insertion_point(builder_scope:Person)
  }

  // @@protoc_insertion_point(class_scope:Person)
  private static final protobuf.Person DEFAULT_INSTANCE;
  static {
    DEFAULT_INSTANCE = new protobuf.Person();
  }

  public static protobuf.Person getDefaultInstance() {
    return DEFAULT_INSTANCE;
  }

  private static final com.google.protobuf.Parser<Person>
      PARSER = new com.google.protobuf.AbstractParser<Person>() {
    @java.lang.Override
    public Person parsePartialFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return new Person(input, extensionRegistry);
    }
  };

  public static com.google.protobuf.Parser<Person> parser() {
    return PARSER;
  }

  @java.lang.Override
  public com.google.protobuf.Parser<Person> getParserForType() {
    return PARSER;
  }

  @java.lang.Override
  public protobuf.Person getDefaultInstanceForType() {
    return DEFAULT_INSTANCE;
  }

}

